### ISSUE TITLE
You have requested a non-existent parameter "setono_sylius_facebook.model.pixel.class".

### ISSUE THREAD

**Issue by land22** [Setono/SyliusFacebookTrackingPlugin#54]
Hello everyone, i have this error with your plugin. So i need to install it in sylius projet . my configurations

this is my bundles.php 
![image](https://user-images.githubusercontent.com/31470119/165190375-a43bb672-01e9-4a34-a186-a96ad1519c68.png)
this is my _sylius.yaml 
![image](https://user-images.githubusercontent.com/31470119/165190464-d0619871-90da-45f6-abde-bd12ac7ddc86.png)
this is my setono_sylius_facebook.yaml
![image](https://user-images.githubusercontent.com/31470119/165190562-3c3a5aea-a5da-4e5b-8f5a-80a9af27107f.png)
 when i try 
`php bin/console doctrine:migrations:diff`
i have error
You have requested a non-existent parameter "setono_sylius_facebook.model.pixel.class".

pls something to fix it thanks

**Comment by loevgaard** [comment]
Try to move up the plugin in `bundles.php`. I am pretty sure this must be the reason :)

**Comment by land22** [comment]
@loevgaard  thank you. It's fine now !!!
