### ISSUE TITLE
[Bug]: Missing composer require

### ISSUE THREAD

**Issue by Loocos** [Setono/SyliusFacebookTrackingPlugin#73]
### Plugin version

v3.0.0

### Sylius version

v1.10.0

### What happened?

Hi,

The installation went fine but when testing, Facebook test event didn't receive anything from my application including your plugin.

So after investigation, I saw than we've to require 2 mandatory bundles to make the event works properly : 
- composer require kriswallsmith/buzz
- composer require nyholm/psr7
But nothing was telling me to require them, no error, no indication in the readme. 

Could be great to add it in the readme ? Will be time saving for people trying to make it work.

**Comment by loevgaard** [comment]
I will have to look into this. The reason these libs are not required is because they are 'abstracted'. The idea is that users can choose their own http client implementation.

**Comment by Loocos** [comment]
Ok I get it, then I think we should tell people to care of this in the README.
The choice to : 
- Choose their own http client
or
- install the default http client

What do you think ? I can make the PR

**Comment by loevgaard** [comment]
Yes, good idea. Would be great with a PR :)

**Comment by Loocos** [comment]
> Yes, good idea. Would be great with a PR :)

PR done
