### ISSUE TITLE
[Bug]: Invalid fbp data sent

### ISSUE THREAD

**Issue by Loocos** [Setono/SyliusFacebookTrackingPlugin#74]
### Plugin version

v3.0.0

### Sylius version

v1.10

### What happened?

Hi,

Just got this warning from Meta, did you have it too ?

### Relevant log output

```shell
Server Sending Invalid Match Key Parameters for ViewContent Event

Your server is sending an invalid fbp parameters value for your ViewContent event. This may be because there was an error in the parameter value.
This may cause issues with the attribution and delivery optimization of ad campaigns that are using this event.
```

**Comment by loevgaard** [comment]
Hmm. Do you have more information from Meta? I mean what parameters specifically

**Comment by Loocos** [comment]
> Hmm. Do you have more information from Meta? I mean what parameters specifically

Nothing more, I just checked again today, and the message has dissapeared. Maybe because the data have taken time to sync with the meta dashboard.
So let close it, will back to this topic if the error appear again.

You'vnt notice that on your side ?

**Comment by loevgaard** [comment]
No, I haven't seen this issue in our dashboard. Thank you for following up on the issue :)
